### ISSUE TITLE
Not working in v74

### ISSUE THREAD

**Issue by r-a-y** [jingyu9575/privileged-mouse-gestures#1]
Thanks for creating such a useful addon, jingyu9575!

I just updated to Firefox v74 and your extension is no longer working.  I'm using Firefox Unbranded.  Let me know if you need any more details from me.

Update - I just checked the "Mapping" tab and all the custom commands are missing. Hitting the `+ Add`  button to re-add the gestures doesn't do anything.

**Comment by jingyu9575** [comment]
The preference `extensions.legacy.enabled` has been renamed to `extensions.experiments.enabled`. Enable it in about:config.

You may need to disable and enable the extension after setting the preference. It seems that Firefox won't automatically re-enable privileged extensions.

**Comment by r-a-y** [comment]
Thanks! Toggling `extensions.experiments.enabled` to `true` worked for me.
