### ISSUE TITLE
Not working in v101

### ISSUE THREAD

**Issue by r-a-y** [jingyu9575/privileged-mouse-gestures#6]
Hi, just upgraded to Firefox v101 and the addon doesn't seem to work anymore.

I see the following message in the debugger:

```
Uncaught (in promise) Error: An unexpected error occurred
    apply self-hosted:2669
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:693
    wrapPromise resource://gre/modules/ExtensionCommon.jsm:941

```

The mouse trace is still able to draw correctly, but the gesture doesn't fire the action.

**Comment by jingyu9575** [comment]
This extension uses JSActor for actions such as back/forward. I found that Firefox 101 refuses to load JSActor files in extensions. 

One workaround is to write the JSActor files to the userChrome folder and let Firefox load it there. Of course this leaves the script there even if the extension is uninstalled.

**Comment by jingyu9575** [comment]
I've found another workaround. Could you test if v0.4 works for you?

**Comment by r-a-y** [comment]
Confirmed that v0.4 is working fine. Thanks for updating the addon, jingyu9575!
